apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: genai-k8s
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
