apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: genai-k8s
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
